import os
import duckdb

# 1. กำหนดพาธไฟล์ฐานข้อมูล
db_path = "indohotel/dev.duckdb"

# 2. เช็กว่าไฟล์มีอยู่จริงหรือไม่ก่อนเชื่อมต่อ
if not os.path.exists(db_path):
    print(f"❌ หาไฟล์ไม่พบที่: {os.path.abspath(db_path)}")
    print("กรุณาตรวจสอบว่าอยู่ในโฟลเดอร์ W:\\Learn_Program\\mini_project และมีไฟล์ indohotel/dev.duckdb อยู่จริง")
else:
    # 3. เชื่อมต่อฐานข้อมูล
    conn = duckdb.connect(db_path)

    # 4. ดึงรายชื่อ Table ใน schema 'main'
    tables = conn.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'main'").fetchall()

    print("Tables in dev.duckdb:")
    if not tables:
        print("  (ไม่พบข้อมูล Table ใน schema 'main')")
    else:
        for table in tables:
            print(f"  - {table[0]}")

    print("\n" + "=" * 80)

    # 5. ดึงข้อมูล 20 แถวแรกแปลงเป็น DataFrame โดยตรง
    try:
        stg_bookings_df = conn.execute("SELECT * FROM main.stg_bookings").df()
        stg_daily_occupancy_df = conn.execute("SELECT * FROM main.stg_daily_occupancy").df()
        stg_employee_performance_df = conn.execute("SELECT * FROM main.stg_employee_performance").df()
        stg_employees_df = conn.execute("SELECT * FROM main.stg_employees").df()
        stg_event_bookings_df = conn.execute("SELECT * FROM main.stg_event_bookings").df()
        stg_financial_summary_df = conn.execute("SELECT * FROM main.stg_financial_summary").df()
        stg_fnb_inventory_df = conn.execute("SELECT * FROM main.stg_fnb_inventory").df()
        stg_fnb_outlets_df = conn.execute("SELECT * FROM main.stg_fnb_outlets").df()
        stg_fnb_transactions_df = conn.execute("SELECT * FROM main.stg_fnb_transactions").df()
        stg_fnb_waste_log_df = conn.execute("SELECT * FROM main.stg_fnb_waste_log").df()
        stg_guests_df = conn.execute("SELECT * FROM main.stg_guests").df()
        stg_housekeeping_log_df = conn.execute("SELECT * FROM main.stg_housekeeping_log").df()
        stg_ingredient_price_history_df = conn.execute("SELECT * FROM main.stg_ingredient_price_history").df()
        stg_maintenance_tickets_df = conn.execute("SELECT * FROM main.stg_maintenance_tickets").df()
        stg_payroll_df = conn.execute("SELECT * FROM main.stg_payroll").df()
        stg_pricing_history_df = conn.execute("SELECT * FROM main.stg_pricing_history").df()
        stg_properties_df = conn.execute("SELECT * FROM main.stg_properties").df()
        stg_recipe_bom_df = conn.execute("SELECT * FROM main.stg_recipe_bom").df()
        stg_role_permissions_df = conn.execute("SELECT * FROM main.stg_role_permissions").df()
        stg_rooms_df = conn.execute("SELECT * FROM main.stg_rooms").df()
        stg_spa_bookings_df = conn.execute("SELECT * FROM main.stg_spa_bookings").df()
        stg_staff_shifts_df = conn.execute("SELECT * FROM main.stg_staff_shifts").df()
        stg_venues_df = conn.execute("SELECT * FROM main.stg_venues").df()
        print("===================== stg bookings =====================")
        print(stg_bookings_df.columns)
        print(stg_bookings_df)
        print("===================== stg daily occupancy =====================")
        print(stg_daily_occupancy_df.columns)
        print(stg_daily_occupancy_df)
        print("===================== stg employee performance =====================")
        print(stg_employee_performance_df.columns)
        print(stg_employee_performance_df)
        print("===================== stg employees =====================")
        print(stg_employees_df.columns)
        print(stg_employees_df)
        print("===================== stg event bookings =====================")
        print(stg_event_bookings_df.columns)
        print(stg_event_bookings_df)
        print("===================== stg financial summary =====================")
        print(stg_financial_summary_df.columns)
        print(stg_financial_summary_df)
        print("===================== stg fnb inventory =====================")
        print(stg_fnb_inventory_df.columns)
        print(stg_fnb_inventory_df)
        print("===================== stg fnb outlets =====================")
        print(stg_fnb_outlets_df.columns)
        print(stg_fnb_outlets_df)
        print("===================== stg fnb transactions =====================")
        print(stg_fnb_transactions_df.columns)
        print(stg_fnb_transactions_df)
        print("===================== stg fnb waste log =====================")
        print(stg_fnb_waste_log_df.columns)
        print(stg_fnb_waste_log_df)
        print("===================== stg guests =====================")
        print(stg_guests_df.columns)
        print(stg_guests_df)
        print("===================== stg housekeeping log =====================")
        print(stg_housekeeping_log_df.columns)
        print(stg_housekeeping_log_df)
        print("===================== stg ingredient price history =====================")
        print(stg_ingredient_price_history_df.columns)
        print(stg_ingredient_price_history_df)
        print("===================== stg maintenance tickets =====================")
        print(stg_maintenance_tickets_df.columns)
        print(stg_maintenance_tickets_df)
        print("===================== stg payroll =====================")
        print(stg_payroll_df.columns)
        print(stg_payroll_df)
        print("===================== stg pricing history =====================")
        print(stg_pricing_history_df.columns)
        print(stg_pricing_history_df)
        print("===================== stg properties =====================")
        print(stg_properties_df.columns)
        print(stg_properties_df)
        print("===================== stg recipe bom =====================")
        print(stg_recipe_bom_df.columns)
        print(stg_recipe_bom_df)
        print("===================== stg role permissions =====================")
        print(stg_role_permissions_df.columns)
        print(stg_role_permissions_df)
        print("===================== stg rooms =====================")
        print(stg_rooms_df.columns)
        print(stg_rooms_df)
        print("===================== stg spa bookings =====================")
        print(stg_spa_bookings_df.columns)
        print(stg_spa_bookings_df)
        print("===================== stg staff shifts =====================")
        print(stg_staff_shifts_df.columns)
        print(stg_staff_shifts_df)
        print("===================== stg venues =====================")
        print(stg_venues_df.columns)
        print(stg_venues_df)


        df_date = conn.execute("SELECT * FROM main.dim_date ").df()
        df_employee = conn.execute("SELECT * FROM main.dim_employee ").df()
        df_fnb_outlet = conn.execute("SELECT * FROM main.dim_fnb_outlet ").df()
        df_guest = conn.execute("SELECT * FROM main.dim_guest ").df()
        df_property = conn.execute("SELECT * FROM main.dim_property ").df()
        df_room = conn.execute("SELECT * FROM main.dim_room ").df()
        df_venue = conn.execute("SELECT * FROM main.dim_venue ").df()
        df_f_ancillary_services = conn.execute("SELECT * FROM main.fact_ancillary_services ").df()
        df_f_fnb_operations = conn.execute("SELECT * FROM main.fact_fnb_operations ").df()
        df_f_hotel_bookings = conn.execute("SELECT * FROM main.fact_hotel_bookings ").df()
        df_f_hotel_operations_hr = conn.execute("SELECT * FROM main.fact_hotel_operations_hr ").df()
        df_event_type = conn.execute("SELECT * FROM main.dim_event_type ").df()
        df_f_daily_occupancy = conn.execute("SELECT * FROM main.fact_daily_occupancy ").df()
        df_f_financials = conn.execute("SELECT * FROM main.fact_financial_summary ").df()

        print("DataFrames loaded successfully:")
        print("===================== date =====================")
        print(df_date.columns)
        print(df_date)
        print("===================== employee =====================")
        print(df_employee.columns)
        print(df_employee)
        print("===================== fnb_outlet =====================")
        print(df_fnb_outlet.columns)
        print(df_fnb_outlet)
        print("===================== guest =====================")
        print(df_guest.columns)
        print(df_guest)
        print("===================== property =====================")
        print(df_property.columns)
        print(df_property)
        print("===================== room =====================")
        print(df_room.columns)
        print(df_room)
        print("===================== venue =====================")
        print(df_venue.columns)
        print(df_venue)
        print("===================== ancillary_services =====================")
        print(df_f_ancillary_services.columns)
        print(df_f_ancillary_services)
        print("===================== fnb_operations =====================")
        print(df_f_fnb_operations.columns)
        print(df_f_fnb_operations)
        print("===================== hotel_bookings =====================")
        print(df_f_hotel_bookings.columns)
        print(df_f_hotel_bookings)
        print("===================== hotel_operations_hr =====================")
        print(df_f_hotel_operations_hr.columns)
        print(df_f_hotel_operations_hr)
        print("===================== event_type =====================")
        print(df_event_type.columns)
        print(df_event_type)
        print("===================== daily_occupancy =====================")
        print(df_f_daily_occupancy.columns)
        print(df_f_daily_occupancy)
    except Exception as e:
        print(f"เกิดข้อผิดพลาดขณะ Query: {e}")

    conn.close()